const express = require("express");
const multer = require("multer");
const { storage } = require("../config/cloudinary");
const upload = multer({ storage });
const router = express.Router();
const authController = require("../controllers/auth");
const { signupSchema, editUserSchema } = require("../validators/user");
const { signinSchema, googleSignInSchema, updateLocationSchema, updatePhoneNumberSchema } = require("../validators/auth");
const validate = require("../middleware/validate");
const auth = require("../middleware/auth");
const checkOwnership = require("../middleware/checkOwnership");

router.post("/signup", validate(signupSchema), authController.signup);
router.post("/signin", validate(signinSchema), authController.signin);
router.post("/google", validate(googleSignInSchema), authController.googleSignIn);
router.patch("/users/:id/edit", auth, checkOwnership, validate(editUserSchema), authController.editUser);
router.patch("/cart/:id/", auth, checkOwnership, authController.updateUserCart);
router.patch("/:id/update-image", auth, checkOwnership, upload.single("avatar"), authController.updateUserImage);
router.patch("/users/:id/location", auth, checkOwnership, validate(updateLocationSchema), authController.updateLocation);
router.patch("/users/:id/phone", auth, checkOwnership, validate(updatePhoneNumberSchema), authController.updatePhoneNumber);
router.get("/check-token", authController.checkToken);
router.post("/logout", authController.logout);
module.exports = router;
